postgres:
    dsn: postgres://postgres:postgres@postgres:5432/dega?sslmode=disable
keto:
    url: http://keto:4466
kavach:
    url: http://kavach-server:8000
meili:
    key: password
    url: http://meilisearch:7700
google:
    key: AIzaSyAY_mt5yHygOLcezc4QVWTwTeyJImloNCM    
mode: development